name: Linter check
on: [push]
jobs:
  tests-and-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install package
        run: pip install .

      - name: Install pylint
        run: pip install pylint

      - name: Run linter
        run: pylint jellyfish
