name: Linter check
on: [push]
jobs:
  tests-and-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          python-version: '3.10'
          architecture: 'x64'

      - name: Update PIP
        run: pip install --upgrade pip

      - name: Install package
        run: pip install .

      - name: Install pylint
        run: pip install pylint

      - name: Run linter
        run: pylint jellyfish
