name: Linter check
on: [push]
jobs:
  tests-and-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

#      (TODO): fix zigzag lib dependency
      - name: Install zigzag library dependencies
        run: pip install numpy cython

      - name: Install package
        run: pip install .

      - name: Run linter
        run: pylint jellyfish
