name: Tests and coverage
on: [push]
jobs:
  tests-and-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

#      (TODO): fix zigzag lib dependency
      - name: Install zigzag library dependencies
        run: pip install numpy cython

      - name: Install package
        run: pip install .

      - name: Run linter
        run: pylint jellyfish

      - name: Generate coverage report
        run: pytest --cov . --cov-report xml:/home/runner/coverage.xml --cov-fail-under=92
      - uses: codecov/codecov-action@v2
        with:
          files: /home/runner/coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
